### ISSUE TITLE
Add wifi support on RPI Zero Wifi

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#220]
Connected to https://github.com/resin-os/resin-os-device-support/issues/4

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_19r9)

**Comment by agherzan** [comment]
Reopening this as it seems that it was not fixed only by having the firmware available. It needs dtb too.

**Comment by pimterry** [comment]
Relates to https://github.com/resin-os/resinos/issues/231

**Comment by telphan** [comment]
Realtes to #245

**Comment by telphan** [comment]
Relates to raspberrypi/firmware#785

**Comment by lfarkas** [comment]
does the latest resin image ie: 2.0.0+rev2-4.1.1-42b3340f8c2c contain support for pi zero w? since i'm just try it and doesn't seems so.

**Comment by agherzan** [comment]
No @lfarkas . This issue will be updated when that happens.

**Comment by muchanem** [comment]
Will this be fixed by v2.0.0+rev3?

**Comment by RyanBalfanz** [comment]
Any updates on this? I'm still not able to use a Pi Zero W with Resin.

**Comment by telphan** [comment]
@RyanBalfanz we are in the process of releasing. The new 2.0.3 will include Pi Zero W. The update should hit the Pi family later today.

**Comment by RyanBalfanz** [comment]
@telphan That's great news! Thanks for the update!

**Comment by telphan** [comment]
@RyanBalfanz Just want to let you know that we have release on Friday as scheduled. Enjoy the new Pi Zero W support.

**Comment by RyanBalfanz** [comment]
@telphan Confirmed! I tested the latest release this past weekend on a Zero W using WiFi and it worked perfectly. Thanks for the update!

**Comment by hellais** [comment]
Which dev image can be downloaded that will support Pi Zero W?

**Comment by agherzan** [comment]
@hellais Sorry for the late answer. I confirm that is indeed the correct image.
